//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMDance.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMDance.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Machine&gt;
        ///  &lt;Name&gt;Lathe&lt;/Name&gt;
        ///  &lt;Description&gt;Lathe setup file&lt;/Description&gt;
        ///  &lt;AbsArcCenter&gt;False&lt;/AbsArcCenter&gt;
        ///  &lt;LatheMinus&gt;False&lt;/LatheMinus&gt;
        ///  &lt;HelixPitch&gt;False&lt;/HelixPitch&gt;
        ///  &lt;BlockSkip&gt;/*&lt;/BlockSkip&gt;
        ///  &lt;Comments&gt;()&lt;/Comments&gt;
        ///  &lt;Endmain&gt;M30&lt;/Endmain&gt;
        ///  &lt;MachineType&gt;LATHEDIA&lt;/MachineType&gt;
        ///  &lt;RotaryAxis&gt;X&lt;/RotaryAxis&gt;
        ///  &lt;RotaryDir&gt;CW&lt;/RotaryDir&gt;
        ///  &lt;Precision&gt;4&lt;/Precision&gt;
        ///  &lt;ProgramId&gt;:$O&lt;/ProgramId&gt;
        ///  &lt;SubReturn&gt;M99&lt;/SubReturn&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Lathe {
            get {
                return ResourceManager.GetString("Lathe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Machine&gt;
        ///  &lt;Name&gt;Mill&lt;/Name&gt;
        ///  &lt;Description&gt;Milling setup file&lt;/Description&gt;
        ///  &lt;AbsArcCenter&gt;False&lt;/AbsArcCenter&gt;
        ///  &lt;LatheMinus&gt;False&lt;/LatheMinus&gt;
        ///  &lt;HelixPitch&gt;False&lt;/HelixPitch&gt;
        ///  &lt;BlockSkip&gt;/*&lt;/BlockSkip&gt;
        ///  &lt;Comments&gt;()&lt;/Comments&gt;
        ///  &lt;Endmain&gt;M30&lt;/Endmain&gt;
        ///  &lt;MachineType&gt;MILL&lt;/MachineType&gt;
        ///  &lt;RotaryAxis&gt;X&lt;/RotaryAxis&gt;
        ///  &lt;RotaryDir&gt;CCW&lt;/RotaryDir&gt;
        ///  &lt;Precision&gt;4&lt;/Precision&gt;
        ///  &lt;ProgramId&gt;:$O&lt;/ProgramId&gt;
        ///  &lt;SubReturn&gt;M99&lt;/SubReturn&gt;
        ///  &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Mill {
            get {
                return ResourceManager.GetString("Mill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Устройство недоступно.
        /// </summary>
        internal static string StringDevIsUnavailable {
            get {
                return ResourceManager.GetString("StringDevIsUnavailable", resourceCulture);
            }
        }
    }
}
